### ISSUE TITLE
Catalyst Build

### ISSUE THREAD

**Issue by joeyboey** [mologie/nxboot#4]
Hey,

could you add a download link to a catalyst build?
I don't seem to find it anywhere. I tried building myself, there are a few `AppCenter` Frameworks missing.

**Comment by joeyboey** [comment]
duplicate of #3

**Comment by mologie** [comment]
Hi, the Catalyst build is not done or public. However it does work, and you can build it yourself by downloading and inserting the AppCenter frameworks from Microsoft if need be, or remove the relevant AppCenter integration code from the app. AppCenter merely provides update notifications and statistics and is not relevant for main functionality.

The official macOS build of NXBoot has no GUI (and is not Catalyst either), and indeed info on how to find it is repeated in #3.
