### ISSUE TITLE
Any way this could be installed through AltStore?

### ISSUE THREAD

**Issue by peabnuts123** [mologie/nxboot#5]
Hey I think this would be very useful but I don't have plans to jailbreak my phone. I don't know a lot about iOS development but at a high-level it seems like this app should be able to run in user-space and not actually require any priv-esc or working around the OS, so I was wondering if this app would work if it was installed through AltStore instead of Cydia? I understand it probably needs to be recompiled to produce an `.ipa` file but it would be great if that is possible and could be published as a release or something. There may be technical details I am unfamiliar with though so I understand if that's not the case.

**Comment by mologie** [comment]
Hi, please refer to the first question in the FAQ:

> *I don't have a jailbreak. Can this work as self-signed IPA too?*
> No, it is impossible. A self-signed IPA does not grant any sandbox exceptions, which NXBoot requires for raw USB device access.

**Comment by peabnuts123** [comment]
Ah, thankyou! I must have missed that. Makes sense.
