### ISSUE TITLE
Repo cannot be added to Sileo on Dopamine (rootless)

### ISSUE THREAD

**Issue by ceedveed** [mologie/nxboot#9]
Dopamine is out of beta. I tried adding your repo, but I can't install nxboot. I'm guessing some dependency is not compatible with rootless. 

Is it possible for you to investigate and maybe update?

Dopamine 1.0.2
iPhone mini 13
iOS 15.1.1

**Comment by mologie** [comment]
Hi, I do not have any jailbreakable devices compatible with Dopamine with me unfortunately. If you could post any details to what fails when adding the repo or installing nxboot then I might be able to investigate w/o device.

**Comment by ceedveed** [comment]
> Hi, I do not have any jailbreakable devices compatible with Dopamine with me unfortunately. If you could post any details to what fails when adding the repo or installing nxboot then I might be able to investigate w/o device.

Dopamine uses Sileo. Sileo does not allow rootful tweaks, apps, etc. to show. So I cannot even add the repo. By default, Sileo search engine also shows NXBoot as a search result, but it will not the associated repo because it is rootful. At least this is my guess.

**Comment by mologie** [comment]
Okay, I will see to read into this whole rootless stuff on the next rainy weekend and try to source some compatible device o/

**Comment by 0x8ff** [comment]
@mologie Apple introduced a mitigation in iOS 15 called SSV which is called [Signed System Volume](https://support.apple.com/guide/security/signed-system-volume-security-secd698747c9/web). If you try to write to anything other than /private/preboot your phone gets bootlooped and is unrepairable, unless you send it to Apple on which they refuse to fix it once the limited warranty runs out

**Comment by 0x8ff** [comment]
So the jb community moved away from putting things into ``/`` (root) and now it's a mess because there's the ``/var/jb`` symlink is in ``/private/preboot/idnumber`` so all previous tweaks compiled to worn on root won't work

**Comment by 0x8ff** [comment]
Better source of info then my tldr: https://www.reddit.com/r/jailbreak/comments/110le54/discussion_what_does_rootless_mean_for_end_users/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by mologie** [comment]
Appreciate the explanation but since this is not a tweak and there is barely any information on how to package for rootless jailbreaks with Sileo etc I'm still stuck on what exactly goes wrong for rootless jailbreaks.

NXBoot is just an application in /Applications.

**Comment by nyathea** [comment]
> Appreciate the explanation but since this is not a tweak and there is barely any information on how to package for rootless jailbreaks with Sileo etc I'm still stuck on what exactly goes wrong for rootless jailbreaks.
> 
> NXBoot is just an application in /Applications.

Hello did you ever get around to figuring this out? Rootless has progressed a lot since this point and I would also be interested in an trollstore compatible version if possible.

**Comment by nyathea** [comment]
Also i tried putting the comand line tool for nxboot in /var/jb/usr/bin and it just returns zsh: killed nxboot. I used chmod 755 on the executable but no luck.

**Comment by mologie** [comment]
Yup, there is a macOS and rootless JB version on a separate branch that I created last Christmas, but I did not get around finishing it. I suppose it's time to dig that stuff out again eventually (hopefully before next Christmas, hah).

A TrollStore preview is available at https://github.com/mologie/nxboot/issues/6#issuecomment-1596181603. That version still had a bug where it crashes after editing the first payload, but that's a one-time issue and it's functional other than that issue.

**Comment by nyathea** [comment]
> Yup, there is a macOS and rootless JB version on a separate branch that I created last Christmas, but I did not get around finishing it. I suppose it's time to dig that stuff out again eventually (hopefully before next Christmas, hah).
> 
> A TrollStore preview is available at [#6 (comment)](https://github.com/mologie/nxboot/issues/6#issuecomment-1596181603). That version still had a bug where it crashes after editing the first payload, but that's a one-time issue and it's functional other than that issue.

Oh thank you. I didn’t notice this

**Comment by olivertzeng** [comment]
@mologie mind to change the title to "Rootless support"?

**Comment by mologie** [comment]
It should be possible to import the repo and install on rootless JBs now. I unfortunately still do not have a test device at hand, but a colleague successfully tested with a beta version. Please ping me here if this is not resolved, so that I can reopen. Thanks!
